# Generated by Django 3.2.5 on 2021-08-31 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_favourite_favouriteitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='status',
        ),
    ]
